Add controllers
Nikolas7zip/java-shareit pull request #1
Opened 2022-10-26 08:31 UTC by Nikolas7zip

also models, services and repositories for user and item, repository in memory

2022-10-26 19:26 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-10-26 19:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/BadRequestException.java
> +package ru.practicum.shareit.exception;
`pom` файл не менялся.
Напишу коммент в произвольном месте...

1. Хорошей практикой будет указать кодировку
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`
2. Я советую всем соблюдать некий порядок при объявлении зависимостей.
Сначала "главный" `spring` все его зависимости и всё о нём.
Потом по степени "тяжеловестности" остальные зависимости. Ну и у меня в проекте, например, последними идёт еще одна секция наши собственные библиотеки/модули/контракты.

2022-10-26 19:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.warn(ex.toString());
Логировать, в некоторых моментах, важно со стектрейсом
`log.info("500 {}", e.getMessage(), e);`

2022-10-26 19:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/InMemoryItemRepository.java
> +        } else {
Тут можно и нужно обходиться без `else`. Ни к чему лишний отступ.
Кроме этого можно настроить вот такое выравнивание.

```
    public List<Item> findItemsToRentByText(String text) {
        if (text == null || text.isBlank()) {
            return Collections.emptyList();
        }

        return items.values()
                    .stream()
                    .filter(item -> {
                        String name = item.getName().toLowerCase();
                        String description = item.getDescription().toLowerCase();
                        return item.isAvailable() && (name.contains(text) || description.contains(text));
                    })
                    .collect(Collectors.toList());
    }
```

2022-10-26 19:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    ItemDto getItem(Long userId, Long id);
Ну вот же только что я видел интерфейс репозитория с хорошими названиями методов...
Почему же тут снова в название методов влезло `Item`
Не добавляй, оно ни к чему...

`createNewItem` - понятно же что создаём новый, поэтому просто -> `create`

2022-10-26 19:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Optional<Item> itemOptional = itemRepository.getById(id);
Пользуйся Optional... и его методом orElseThrow

2022-10-26 19:26 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    Optional<User> getByEmail(String email);
Вообще в репозиториях можно было бы использовать глагол `find`, а в сервисах `get`

2022-10-26 19:26 UTC, FanaticFiz commented on src/main/resources/application.properties
> +#spring.config.activate.on-profile=ci,test
Снова буду топить за то чтобы ты привыкал к написанию файла свойств для приложения в формате `yaml -> application.yml`
Мне трудно сейчас представить проект в котором до сих пор на него не пересели!

Попрошу тебя этому следовать.

2022-10-27 10:26 UTC, Nikolas7zip commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        Optional<Item> itemOptional = itemRepository.getById(id);
Это я еще вспомнил про Optional)

2022-10-27 10:28 UTC, Nikolas7zip commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    ItemDto getItem(Long userId, Long id);
Да, было бы круто, если давали по учебе рекомендации как именовать функции в сервисах, репозиториях, контроллере)

2022-10-27 19:03 UTC, FanaticFiz approved these changes

2022-10-27 19:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    User add(User user);
Ну а что на счёт того чтобы вывести из одинаковых интерфейсов один общий и универсальный?

2022-10-27 19:03 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        User user = userRepository.findById(id).orElseThrow(() ->
- Лучше выносить каждую операцию на новую строку
- Можно импортировать статик предварительно

```
    @Override
    public UserDto get(Long id) {
        User user = userRepository.findById(id)
                                  .orElseThrow(() -> new EntityNotFoundException("User id=" + id + " not found"));

        return mapToUserDto(user);
    }
```

2022-11-09 07:37 UTC, merged