Add bookings
Nikolas7zip/java-shareit pull request #2
Opened 2022-11-14 13:23 UTC by Nikolas7zip

2022-11-14 19:14 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-14 19:14 UTC, FanaticFiz commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
Что то не взлетело в свойствах?

2022-11-14 19:14 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "start_date")
Не хватает указания что поле не может быть null, как в БД.

2022-11-14 19:14 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingPredicates.java
> +    public static Predicate<Booking> isWaiting() {
Классно ты организовал тут всё, прям не хочется тебя и ругать ))

Но получается вот что. 
Вместо того чтобы возложить поиск на БД, построив соответствующие запросы, ты выполняешь только часть работы...

2022-11-14 19:14 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query(" select b from Booking b " +
Оформляй запросы, набирая команды SQL в верхнем регистре: SELECT

2022-11-14 19:14 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        validateBooking(booking);
Если собрался в методе бросать ексепшн, то назови метод соответствующе.

2022-11-14 19:14 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        booking.setStatus(isApproved ? BookingStatus.APPROVED : BookingStatus.REJECTED);
Тернарник очень кстати!
Заимпорти статики, будет читабельнее...

`booking.setStatus(isApproved ? APPROVED : REJECTED);`
`return mapToBookingOutput(bookingRepository.save(booking));`

2022-11-14 19:14 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        return BookingMapper.mapToBookingOutput(bookingRepository.save(booking));
А вот `bookingRepository.save(booking)` это основное действие тут, лучше его не "прятать", оно достойно отдельной строки кода...

2022-11-14 19:14 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @Column(name = "owner_id")
Ты в предыдущей сущности хорошо все поля прописывал, почти ничего не забыл...
Тут тоже not null не хватает и возможно длин строк.

2022-11-16 12:39 UTC, Nikolas7zip commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
В теории не все рассказали об аннотациях для hibernate и рекомендовали базу расписывать через schema.sql

2022-11-16 12:40 UTC, Nikolas7zip commented on src/main/java/ru/practicum/shareit/booking/BookingPredicates.java
> +    public static Predicate<Booking> isWaiting() {
да уж, с предикатами неплохо получилось бы))

2022-11-16 18:18 UTC, FanaticFiz approved these changes
Принимается

2022-11-25 07:16 UTC, merged