feature: add item requests, pagination and tests
Nikolas7zip/java-shareit pull request #3
Opened 2022-12-01 18:50 UTC by Nikolas7zip

2022-12-03 10:40 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-03 10:40 UTC, FanaticFiz commented on src/main/resources/application.properties
> +#spring.config.activate.on-profile=ci,test
А почему мы с тобой еще не перешли на YAML формат???

https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.properties-and-configuration.yaml

2022-12-03 10:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    public boolean equals(Object o) {
Кстати! 
Рекомендуем не добавлять `equals/hashcode` в `entity`

Ознакомься
https://habr.com/ru/company/haulmont/blog/564682/

2022-12-03 10:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public List<BookingOutput> getByBooker(Long bookerId, QueryBookingState state, EntityPagination pagination) {
А не лучше было бы инвертировать условие в методе `get` 
Как то привычнее видеть `return` в конце...

```
    @Override
    public BookingOutput get(Long userId, Long bookingId) {
        Booking booking = bookingRepository.findById(bookingId)
                                           .orElseThrow(() -> new EntityNotFoundException(Booking.class, bookingId));
        if (!booking.getBooker().getId().equals(userId) && !booking.getItem().getOwnerId().equals(userId)) {
            throw new EntityNotFoundException(Booking.class, bookingId);
        }

        return BookingMapper.mapToBookingOutput(booking);
    }
```

2022-12-03 10:40 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        EntityPagination pagination = new EntityPagination(from, size);
Ну сделай красиво!

Посмотри на `PageRequest.of()` повтори статический метод `of` в своём паджинаторе...

Хотя я и не очень его приветствую, но пусть будет, давай только оформим красиво!

Вот так я хочу:

```
    @GetMapping
    public List<ItemDto> getOwnerItems(@RequestHeader(USER_ID_REQUEST_HEADER) Long userId,
                                       @RequestParam(required = false, defaultValue = "0") int from,
                                       @RequestParam(required = false, defaultValue = "10") int size) {
        return itemService.getByOwner(userId, EntityPagination.of(from, size));
    }
```

2022-12-04 09:13 UTC, Nikolas7zip commented on src/main/resources/application.properties
> +#spring.config.activate.on-profile=ci,test
Да, я все перехожу на yaml,  а потом опять .properties возникает))

2022-12-04 09:46 UTC, Nikolas7zip commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        EntityPagination pagination = new EntityPagination(from, size);
Спасибо! Хорошая идея)

2022-12-04 13:15 UTC, FanaticFiz approved these changes

2022-12-13 16:11 UTC, merged